name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade use-secrets activity
        id: check-secrets
        uses: ./.github/actions/check-secrets-action
        with:
          secrets-context: ${{ toJSON(secrets) }}
          your-secret: #your secret here


      # - name: prep payload for upload
      #   run: |
      #     mkdir -p payload-dir
      #     echo ${{steps.check-secrets.output.reports}} >> payload-dir/payload.json

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: lg-payload
      #     path: payload-dir/payload.json
